### ISSUE TITLE
Can not perform immediate find after a document save

### ISSUE THREAD

**Issue by lan-nguyen91** [couchbaselabs/node-ottoman#111]
```
var Furniture = ottoman.model('Fur', { 
   type: { type: 'string' },
})
var test = new Furniture({
  type : 'update',

})
test.save(function(err, doc){
  ottoman.ensureIndices(function(err){
    Furniture.find({type : 'update'}, {}, function(err, myDoc){
      console.log(myDoc);
    })
  })
})
```

I m not sure if I m missing the concept of ottoman modelInstance, 
but the code above returned nothing on the first run, 
the document is being created in the database
but `[]` is the result of the `.find`

All runs after that works, so the result always return 1 document less than the database contained (at least for this example).

**Comment by brett19** [comment]
Hey @lan-nguyen91,
You will need to the consistency parameter on your find to ensure that the database becomes consistent before the search is run, otherwise your search will complete before the internal indexes have completed.  Note that if you have the id of the document, you can do a lookup based on that ID without needing the index.
Cheers, Brett

**Comment by lan-nguyen91** [comment]
Hey @brett19 
im running a bulk insertion and lookup, what is a good way of making sure all the internal index is valid  before i can do the look up like the code above. Assuming that I don't have an ID to look up.

**Comment by brett19** [comment]
Hey @lan-nguyen91, this should do it:
```javascript
    Furniture.find({type : 'update'}, {consistency: ottoman.Consistency. LOCAL}, function(err, myDoc){
      console.log(myDoc);
    });
```

**Comment by lan-nguyen91** [comment]
Hi @brett19 , this is very helpful.

Thanks
