### ISSUE TITLE
Comparison operator in find query

### ISSUE THREAD

**Issue by lan-nguyen91** [couchbaselabs/node-ottoman#116]
Do we support the use of operator like `>,<,==, ...` 

According to [Couchbase comparison operator](http://developer.couchbase.com/documentation/server/current/n1ql/n1ql-language-reference/comparisonops.html) we can build our N1ql using these operator, but i can't seem to find the feature in the current build.

**Comment by moxious** [comment]
cbstore adapter uses a function called find that does generic find.  This gets called when you do `myModel.find({ filter: 'value' })`.   Code here: https://github.com/couchbaselabs/node-ottoman/blob/master/lib/cbstoreadapter.js#L750

Supported filter stuff can be found here:  https://github.com/couchbaselabs/node-ottoman/blob/master/lib/cbstoreadapter.js#L629

In short - no it doesn't look to me like numerical stuff like that is presently supported.  A fluent API for building n1ql queries from ottoman models would be a huge help, but it's quite complex to implement.    In my dream world, we do something like this:

`myModel.find().where({ '>': [ x, 5 ]}).limit(1).skip(4).execute();`

But I think that's a ways off.  The current approach where you take some JSON objects (like filters) and build a n1ql query string from that isn't going to scale very well because of the sheer number of language features for n1ql, and special cases.

**Comment by lan-nguyen91** [comment]
@brett19 @moxious 

https://github.com/lan-nguyen91/node-ottoman/blob/master/lib/cbstoreadapter.js#L623

I did some custom bells and whistles, feel like it suits my need but if you guys are interested, i can make a separate PRs to the codebase.

The way the query structure would be

```User.find({age : { '>' : 5 }}) or 
User.find({first_name : { '$contains' : 'bob }}) ```
