### ISSUE TITLE
support for saving multiple models at once

### ISSUE THREAD

**Issue by DanlanNZ** [couchbaselabs/node-ottoman#126]
Maybe i've missed something but when saving multiple models at once with ottoman, code tends to turn into callback hell for me.
This could be alleviated with Promises but still I think there is a better way to manage this, I've come up with a three possible solutions

```javascript
const ottoman = require('ottoman'),
      Customer = ottoman.model('Customer', {
        name: { type: 'string' },
      },
      Store = ottoman.model('Store', {
        name: { type: 'string' },
        customers: [{ ref: 'Customer' }],
      },
      Product = ottoman.model('Product', {
        name: { type: 'string' },
        store: { ref: 'Store' },
      },
      customer = new Customer({
        name: 'John'
      }),
      store = new Store({
        name: 'Johns Store'
        customers: [customer],
      }),
      product = new Product({
        name: 'Johns Product',
        store: store,
      });

// OPTION 1: deep boolean on save
product.save({ deep: true }, (err) => {
  if (err) throw err;
})

// OPTION 2: explicit model references on save
product.save({ ref: ['store', 'store.customers[*]'] }, (err) => {
  if (err) throw err;
})

// OPTION 3: as an extension to the ottoman prototype
ottoman.save(customer, store, product, (err) => {
  if (err) throw err;
});
```

these would probably all require a way to rollback on error, option one and possibly two could be slow but I think all three options could co-exist. what are the general thoughts about this, would it be worth investigating further?

**Comment by moxious** [comment]
@DanlanNZ see https://github.com/couchbaselabs/node-ottoman/issues/115 - I wrote some stuff there about a possible approach.  The path is clear, it's just a matter of finding the time to write/test the code.  In my own use of Ottoman, I've already wrapped most key functions (create, find, remove) in promises, so it hasn't been a priority for my team to do this as of yet.

My $0.02 is that doing extra stuff with callbacks isn't the right path, and that Ottoman should use promises.  Making the change to ottoman to do this isn't that complex, so that it could support *either style*.

If you're looking for an "in the meantime" solution, I'd investigate Bluebird and "promisify" which will do most of the work for you.

**Comment by DanlanNZ** [comment]
thanks @moxious I had seen Bluebirds promisify function but have not looked into as yet, it sounds like a good first step

**Comment by brett19** [comment]
Hey @DanlanNZ,
While this would certainly be interesting, Couchbase does not currently support atomic saves of documents.  This means that if a save fails due to CAS failure, we would need to rollback as you have mentioned.  The issue is that we do not have access to the original document which was stored on Couchbase at the time of the failure.  In addition to this, its possible that any of the rollback saves may fail without recourse.  This kind of logic is likely best left to the application which can define more consistent constraints on how saving behaves when you want to allow multiple documents to be updated as atomically as possible.
Cheers, Brett
