### ISSUE TITLE
Removing a child document in reference models

### ISSUE THREAD

**Issue by sbehrends** [couchbaselabs/node-ottoman#135]
When I remove a document, that has a parent document, the document is properly deleted, but the references from the parent is not deleted and when querying it it return undefined information.

```
models.User.getById(userId,  {load: ['bikes']}, function(err, user) {
    const willDelete = _.find(user.bikes, function(f) { return f._id === req.params.guid });
    willDelete.remove(function(error) {
      // Here the child is deleted, but not the User reference to the child.
    });
  });
```

**Comment by DanlanNZ** [comment]
AFAIK this is by design, your application should manage cleaning up references. Looking up references on every .remove call would make it a very expensive operation.

You application should do something like this
```javascript
models.User.getById(userId,  {load: ['bikes']}, function(err, user) {
    const willDelete = _.find(user.bikes, function(f) { return f._id === req.params.guid });
    willDelete.remove(function(error) {
      // Here the child is deleted, but not the User reference to the child.
      user.bikes = _.filter(users, { _id: req.params.guid });
      user.save(.function (userSaveError) {
        // Here both child document and parent reference should be removed
      });
    });
  });
```
^^ iterating over user.bikes twice should probably be optimised

an alternative approach might be to add an options parameter to the remove function in order to cleanup references when desired. Something like `model.remove({ withRefs: true }, cb)`
