### ISSUE TITLE
Make pipe delimter configurable

### ISSUE THREAD

**Issue by giggo1604** [couchbaselabs/node-ottoman#141]
Hi,

I just started a new project with ottoman, but i have to use our intern couchebase conventions and we aren't using the pipe as an delimiter in our ids. 

So an option to change this: `User|7b932462-8152-47db-a3b4-1cd76f0af2d4` to for example this `User::7b932462-8152-47db-a3b4-1cd76f0af2d4` would be creat.

I quickly looked at the project and found out that the pipe delimiter is hardcoded and so I changed the project to make the delimiter configurable. However, I would like to ask if you are considering such a feature? I would like to make a pull request but I think my current solution is rather hacky and i would need some guiding in how such a feature is best included into the project.

**Comment by moxious** [comment]
I would ask you to consider a different design approach; the reason keys are needed is because couchbase is a key/value store in the end, but if you're using ottoman, then it allows you to deal with the database a layer higher than that.   I'd recommend considering working with the database in a way that doesn't require any consideration of the keys at all, so this PR wouldn't be necessary.

Could you describe why the delimiter would need to be different?  If this would be done to support "parsing" the keys into different values, I would strongly suggest not doing that, since you can load the document; the OID will be in the _id field, and the "User" will be in the _type field, so it's already parsed for you.

**Comment by giggo1604** [comment]
Thanks for the reply, I see that there is and shouldn’t be an actual value in choosing an alternate delimiter. The thing is that I am working with an existing codebase where they already decided to use a schema like used in this http://blog.couchbase.com/user-profile-store-advanced-data-modeling article and we want to use the same schema just for consistency. I think making the delimiter configurable would not be an issue performance wise and could help consistency when modelling against an existing database.

**Comment by brett19** [comment]
Hey Guys,
This question actually goes a bit beyond simply specifying different delimiters, but also encompasses a case where a user might want a completely different method of concatenating the information in a document to generate the key.  This would be a powerful tool to enable the use of Ottoman.js with existing data-sets not originally designed for it.  I am thinking of some kind of key generation callback or interface, but have not come to a final conclusion yet.
Cheers, Brett

**Comment by gsi-alejandro** [comment]
Solved in Ottoman v2

Passing a keyGenerator function to the globalConfig function, the below code is the default function for keyGenerator, you can override it on your needs.

```
import { globalConfig } from 'ottoman';

globalConfig({
  keyGenerator: ({ metadata, id }) => `${metadata.scopeName}$${metadata.collectionName}::${id}`
});
```
more information in the new documentation https://v2.ottomanjs.com/guides/connections.html#global-config
