### ISSUE TITLE
Model violation doesn't complain

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/node-ottoman#144]
Create a model with a field defined as an integer, then create an instance with a string.  No complaint.  Is this normal?

```
var ottoman = require('ottoman');
var couchbase = require('couchbase');
var cluster = new couchbase.Cluster('couchbase://127.0.0.1');
ottoman.bucket = cluster.openBucket('default');

ottoman.ensureIndices(function() {
    var Movie = ottoman.model('Movie', {
        title: 'string',
        rating: 'string',
        releaseYear: 'integer',
        hasCreditCookie: 'boolean'
    });


    var thor = new Movie({title: 'Thor', rating: 'PG-13', releaseYear: '2011', hasCreditCookie: true });

    thor.save(function(err) {
        if (err) return console.error(err);
        console.dir(thor);
    })


});
```

**Comment by ysimidjiyski** [comment]
I'm having the same issue.  I played with some of the other types too, and 'Date' was the only type that I found that would (sometimes) throw an error if you passed it bad data.  I didn't test the full matrix of [expected, actual] data pairs.

Schema validation is a must-have feature for most users.  Since the official Couchbase documentation points to sample code that defines a schema using ottoman, I was definitely surprised to find this missing.  Knowing what the recommended workaround is and having this documented would be much appreciated (maybe I missed the documentation?).

**Comment by ingenthr** [comment]
@ysimidjiyski we talked a bit about this one and the Ottoman v2, I think, will address this.  @brett19 is working on that now.  Thanks for the additional feedback!

**Comment by gsi-alejandro** [comment]
In Ottoman v2 it was fixed following these rules:
1. try to parse the value to a number, if it's successful, then the document will be store with the value as a number (2011 instead of "2011")
2. if the parse to number fail this error will be thrown "ValidationError: Property releaseYear must be of type Number"

Notice: in Ottoman v2 not exist integer value for now, please use Number instead.
