### ISSUE TITLE
ottoman.validate does not run validation functions for nested objects

### ISSUE THREAD

**Issue by ysimidjiyski** [couchbaselabs/node-ottoman#161]
Given a model with a nested object such as the following:

const Session = ottoman.model('Session', {
    location: {
        longitude: {type: 'number', validator: validators.validateNumber},
        latitude: {type: 'number', validator: validators.validateNumber},
        state: {type: 'string', validator: validators.validateString}
    },
    created_date: {type: 'Date', default: Date.now, validator: validators.validateDate},
    last_access_date: {type: 'Date', default: Date.now, validator: validators.validateDate},
})

ottoman.validate will not run the validation functions specified for longitude, latitude, or state.  This appears to have been fixed on the development branch by 1ce57d3cc7b9e78880c30dd694ba7c62759c2f83 in August of 2016.  However, since that fix is not live -- (as of this writing, v1.0.4 is the latest version, and was released just before that fix went in), I can't install a version of ottoman with the fix via npm install, and so cannot reliably use it in my project.

Please do get this fix released -- it is blocking my ability to adopt ottoman, since schema validation is a must-have for my scenario.

**Comment by brett19** [comment]
Hey @ysimidjiyski,

Unfortunately this issue is actually do to the way that sub-schemas are handled in Ottoman v1.  Ottoman v2 refactors how we do embedding of sub-schemas in the top level schema, and resolves this issue, however the fix is not something we can back-port to Ottoman v1 in a non-breaking way.  We are hoping to have a Beta of Ottoman v2 available soon, I'll be sure to let you know as soon as it is!

Cheers, Brett

**Comment by waffledonkey** [comment]
Before I pull the rest of my hair out does validation work for local properties?  The `"PhoneValidator"` example never receives any input arguments, so it doesn't matter what you pass it will always succeed. 

 The logic cleverly says:
```
if (val && !val.match(phoneno)) {
  throw new Error('Phone number is invalid.');
}
```
but since there is no input arguments being passed (no `val`...) it can never fail.  Try changing that to `!val || !val.match(phoneno)` and it'll fail every time.  Validation is an interesting idea, but seems horribly broken in practice.

> While I have you can I talk you into taking [this](https://blog.couchbase.com/nodejs-odm-couchbase-ottoman/) down.  The interface described there is apparently quite outdated.

**Comment by gsi-alejandro** [comment]
Solved in Ottoman v2

- Schema type validation will run for sub-documents.
- Schema custom validation provides under validator property will run for sub-documents.
