### ISSUE TITLE
Error: not_found: Design document _design/Inventory not found

### ISSUE THREAD

**Issue by danielwwc** [couchbaselabs/node-ottoman#173]
There is an issue with version 1.0.4. There is no error in the previous version.
I have run ensureIndices, and i have checked that there is only _design/otto design document
i tried to change the index type, but there is still no results.
This is running on couchbase sdk version 2.3.4

InventoryModel     
index: {
        findByItemCode: {
            by: 'ItemCode'      
        }

Error messages:
{ Error: not_found: Design document _design/Inventory not found
    at ...\node_modules\couchbase\lib\bucket.js:521:17

**Comment by brett19** [comment]
Hey @justic3,
Have you tried setting the index type to N1QL instead?  GSI based indexes are more reliable in later versions of Couchbase Server and Ottoman.js.
Cheers, Brett

**Comment by justic3** [comment]
I tired setting the index type to refdoc, view, n1ql, however it is not working. 
I have run ensureIndices but it doesnt create the design document. 
but however i will just use the find method 
`inventory.find({ _type: "Inventory", ItemCode: req.params.itemCode }, function (err, done) {`
instead of using
`inventory.findByItemCode(req.params.itemCode, function (err, done) {`

Thanks @brett19, looking for forward to later versions!
