### ISSUE TITLE
I think i can't find remove?

### ISSUE THREAD

**Issue by frank-dspeed** [couchbaselabs/node-ottoman#177]
I see no where a good api way to remove items :)

Maybe i am wrong but there should be a other way then doing find and then
```
Models.find()
bucket.remove(res[0],_id, (err)=>{
console.log(err)
})
```

Isn't there a way to load Models Directly by id and doing something like .delete .remove .destroy?

i see also no where a example of a remove :) only create

**Comment by brett19** [comment]
Hey @frank-dspeed,
You can use the Model.ref('key') function to fetch a unloaded model reference to a particular key.  Note that performing a remove on an unloaded model will only work if that model has no referential indexes in its definition (since we need to know the data of the document to locate those indexes).

Cheers, Brett
