### ISSUE TITLE
Typescript, anybody using it here for node-ottoman ?

### ISSUE THREAD

**Issue by appsolutegeek** [couchbaselabs/node-ottoman#188]
Hi,

Anybody using typescript here for working with node-ottoman ?

I couldn't find a types file at @types on npm.

And one doesn't seem to ship with ottoman

**Comment by mz2** [comment]
@appsolutegeek yes indeed. Me & my team at Manuscripts (https://manuscriptsapp.com) has done some work on this here: https://github.com/mpapp/node-ottoman/ – it's not complete, but at a stage where it's potentially useful also for someone else.

**Comment by mz2** [comment]
My hope is that the type mappings, either ones we've made or someone else's, would be accepted back into the mainline node-ottoman repository like the types in the Couchbase SDK for example are (i.e. in the package itself, rather than via DefinitelyTyped).

**Comment by appsolutegeek** [comment]
Great news, what is left to do on it?

**Comment by mz2** [comment]
@appsolutegeek give it a spin and let's complete it together if you find things that are missing? You can reference the package directly from GitHub (just reference it instead of your regular Ottoman, and they types will magically appear). 

Our experience with these type mappings is for a small microservice related to https://manuscriptsapp.com and as it's just one set of usecases it's quite likely we're missing out some parts of the API in our type mappings.

**Comment by mz2** [comment]
There's a pull request up here: https://github.com/couchbaselabs/node-ottoman/pull/189
