### ISSUE TITLE
<static> applyData(mdlInst, data) give an "applyData is not a function" error

### ISSUE THREAD

**Issue by dalborgo** [couchbaselabs/node-ottoman#211]
`<static> applyData(mdlInst, data)`
```
import { User } from '../models'
...
const user = await User.byId(input.username) //byId is a promisify function
User.applyData(user, input)
```
return "applyData is not a function" error.

-------------------------------------------

`<static> fromData(data)`

`const toSave = User.fromData(input)`

create a new ModelInstance correctly

**Comment by brett19** [comment]
Hey @dalborgo ,
Your probably looking for `ModelInstance.applyData(user, input)`.  Note also that `applyData` should only be used in extremely specialized cases, and `byId` and related functions should typically be used instead.  `applyData` is specifically for populating an object with data that was specifically fetched from the database manually, it skips some forms of processing that would otherwise occur (such as validators).
Cheers, Brett
