### ISSUE TITLE
Question - Use of delay in Start Method

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#303]
From the test cases, it has this method startInTest - https://github.com/couchbaselabs/node-ottoman/blob/7a2fc9747f4b9532d348072f6974e3c0416c33d7/__test__/testData.ts#L14 which does a delay. 

**Any specific reason for that?**

This is a question from the customer, they want to know 

    

-  Is the Start Method where Bootstrapping i.e Connection is established ?
-  In the test as mentioned above why is there a code that use a delay
    `  await delay(700);`
    Does the connection need to wait for anything ?

**Comment by gsi-alejandro** [comment]
startInTest function is the way that was implemented to test Ottoman with the flag ensureCollections in true and false. Also, all the possible start logic will be encapsulated in only one place to make easier the implementation of future changes or fix bugs.

the statement -> await delay(700); was added because of the inconsistency while creating scopes or collections.

1. yes, Ottoman is successfully connected to the Database Server(Cluster)
2. this delay tries to ensure scopes and collections availabilities to run immediately after all the tests implemented.

**Comment by AV25242** [comment]
Thanks @gsi-alejandro, I think this should be handled when we work on scopes and collections configuration and automatic handling of scopes and collections. EnsureCollection method should encapsulate all the logic including retries. Ideally you would await on ensureCollections inside the start method

**Comment by gsi-alejandro** [comment]
This is the way it works. But startInTest is just a High Order Function (HOF) to encapsulate the original start function only for test purposes.
