### ISSUE TITLE
Ottoman Audit - Blackduck Scanning

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#308]
Is Ottoman V2 verified for Vulnerability ? 
does `npm audit` come back clean ?

**Comment by gsi-alejandro** [comment]
Yes, Ottoman was verified for vulnerabilities and pass ok.

Right now npm audit is reporting:
found 4685 vulnerabilities (4682 low, 3 high) in 1725 scanned packages

In order to handle this we propose 2 steps:
1. Keep up-to-date all dependencies
2. Use https://snyk.io/ to progressive track vulnerabilities (add badge to notified about this)

**Comment by AV25242** [comment]
Extending this ticket to do Ottoman Black duck Scans
