### ISSUE TITLE
Model methods argument order consistency

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#310]
Make all Model method arguments for KV Operations consistent  with [underlying SDK ](https://docs.couchbase.com/nodejs-sdk/current/concept-docs/documents.html#primitive-key-value-operations) where id is always in the first arg

Anywhere Id is passed it should be the first argument.

**Comment by gsi-alejandro** [comment]
@AV25242 I checked 2 possible solutions:
1. Implementing function overload
2. Making the first parameter always the id allowing empty string ('') or null values if the id can be extracted from the second parameter (data)

I recommended the second one for this case because the function overload implementation in Typescript produces an additional type with an incorrect signature.

Results
with id value:
`update(id, data);`

with id inside data:
`update(data.id, data);`
or
`update('', data);`
or
`update(null, data);`
