### ISSUE TITLE
Use Node.js 3.2 alpha with Ottoman

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#428]
Can we get Ottoman tested with Couchbase Node.js 3.2 alpha in a feature branch

**Comment by gsi-ariam** [comment]
@AV25242: 
Stable: '3.1.2'
Alpha: '3.2.0-alpha.2'

Testing over couchbase community '6.6.0' & '7.0.0-beta' versions

Sdk Stable vs Alpha, some errors in `couchbase/dist/collectionmanager.js`:

1-> Create Collection:
	 TextError: "requested resource not found."
	 path(alpha): '/pools/default/buckets/`travel-sample`/scopes/`_default`/collections' // throw error
	 path(stabl): '/pools/default/buckets/`travel-sample`/collections/`_default`' // works fine

2-> Create Scope:
	 TextError: "requested resource not found."
	 path(alpha): '/pools/default/buckets/`travel-sample`/scopes' // throw error
	 path(stabl): '/pools/default/buckets/`travel-sample`/collections' // works fine

3-> Drop Scope:
	 TextError: "method not allowed"
	 path(alpha): '/pools/default/buckets/`travel-sample`/scopes/`DummyScopeTestError`' // throw error
	 path(stabl): '/pools/default/buckets/`travel-sample`/collections/`DummyScopeTestError`' // works fine

*- Never throw a `ScopeNotFoundError` caused by bad error parsing in `couchbase/dist/collectionmanager.js`:
```javascript
if (errText.includes('not found') && errText.includes('scope')) { // wrong parse
    throw new errors_1.ScopeNotFoundError(undefined, errCtx);
}
```
The correct way should be:
```javascript
if (errText.includes('scope_not_found')) { // correct parse
    throw new errors_1.ScopeNotFoundError(undefined, errCtx);
}
```

4-> Drop Collection:
	 TextError: "method not allowed"
	 path(alpha): '/pools/default/buckets/`travel-sample`/scopes/`_default`/collections/`DummyCollectionTestError`' // throw error
	 path(stabl): '/pools/default/buckets/`travel-sample`/collections/`_default`/`DummyCollectionTestError`' // works fine

*- Never throw a `CollectionNotFoundError` caused by bad error parsing in `couchbase/dist/collectionmanager.js`:
```javascript
if (errText.includes('not found') && errText.includes('collection')) { // wrong parse
    throw new errors_1.CollectionNotFoundError(undefined, errCtx);
}
```
The correct way should be:
```javascript
if (errText.includes('collection_not_found')) { // correct parse
    throw new errors_1.CollectionNotFoundError(undefined, errCtx);
}
```

5-> When `ottoman.start()` is called:   

```typescript
async start(): Promise<void> {
	await this.ensureCollections();
	await this.ensureIndexes();
}
```

this throw a TypeError on alpha:
 - `TypeError: queryindexmanager_1.QueryIndexManager is not a constructor`

In sdk library `couchbase/dist/cluster.js` Cluster.queryIndexes() method is called:

```javascript
queryIndexes() {
	// Wrong invocation of QueryIndexManager should be:
	// return new queryindexmanager_1(this);
	// that solve the TypeError
    return new queryindexmanager_1.QueryIndexManager(this); // 👎🏼 current implementation
}
```

**Comment by AV25242** [comment]
@gsi-ariam  I have notified @brett19  he will take a look at it shortly.

**Comment by brett19** [comment]
Hey @AV25242, @gsi-ariam,

Some of these issues are actually do the difference between 7.0-GA and 7.0-Beta unfortunately.  Many of the needed changes for GA were performed before the alpha.2 release was made, including changes to collection APIs.  Items 1, 2, 3, 4 all fall under this unfortunately, I'll see if there is some way to make this work in the interim for testing.  The last item there (5) is valid and I'll take a look and get that fixed as soon as possible.

Cheers, Brett
