### ISSUE TITLE
Investigation  - updateById

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#477]
In my tests using try-ottoman and trying to update the address field for Hotel using PATCH which uses updateById under the hood I was not able to get it updated. Either its something I was doing wrong or something is not working. Need to investigate.

**Comment by gsi-ariam** [comment]
I was testing with the source of https://github.com/couchbaselabs/try-ottoman, where I found an error that corresponds to the swagger configuration for which it did not allow me to execute the patch because it required that the `id` be in format `uuid` hence it will not allow the request to be made, since the `id` are numbers not `uuids`, changing this in the swagger.yaml updateById already works correctly
Another detail is that if windows is used in the file `try-ottoman / ottoman-global-config.js` in line 13 `connectionString: 'couchbase: // localhost: 8091' ` the` localhost` should be changed to `127.0 .0.1`

**Comment by AV25242** [comment]
@gsi-ariam I found it too but there is more to just updatebyid can you fix the other methods as well ?

**Comment by AV25242** [comment]
I created this because I couldnt get updateById to work irrespective of me fixing the UUID constraint. Dont close this. I will test once and come up with results today.
