### ISSUE TITLE
Ottoman Testing with SDK 4.0

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#648]
The plan is to get Ottoman over Node.js SDK 4.1 which will release this month, as a step towards getting Ottoman updated it will be good to start testing Ottoman with SDK 4.0, a release with SDK 4.0 is not recommended at this time, this is just a proactive measure to get us to SDK 4.1 in May.

**Comment by ejscribner** [comment]
Tested it out with 4.0; everything worked well with a few minor changes:

`/src/ottoman/ottoman.ts`:
  - removed `NoopTracer` and `NoopMeter` from the import statement (from Couchbase)
  - removed lines 241-247, which appears to have been a temporary solution to a segfault that is hopefully fixed in 4.0

`/src/couchbase.ts`:
  - removed `RequestSpan` from the exports

Additionally, the connection string parameter to ignore TLS verification was renamed from `ssl=no_verify` to `tls_verify=none` in v4.0 (I believe this is due to the change to couchbase++). Connections to TLS-enabled clusters (like Capella) will either need the root certificate passed in with the connection or `?tls_verify=none` at the end of the connection string. 

I wrote a quick tutorial with a bit more info if needed: https://developer.couchbase.com/tutorial-nodejs-tls-connection
