### ISSUE TITLE
Using multiple buckets

### ISSUE THREAD

**Issue by yamsellem** [couchbaselabs/node-ottoman#77]
Ottoman's bucket is initialized through a property (which seems odd, using a function or a constructor make more sense).

```javascript
var ottoman = require('ottoman');
var couchbase = require('couchbase');
var cluster = new couchbase.Cluster('couchbase://127.0.0.1');
ottoman.bucket = cluster.openBucket('default');
```

_But, the important point here is_: is there a way to change this bucket over time?
It does not seems possible to create multiple `ottoman` instance, because the `require('ottoman')` is a already a constructor.

Some models will lies in a specific bucket and other models in another bucket.

So, how to use multiple buckets?
Is Ottoman limited to one bucket for the time being?

Thanks.

**Comment by frank-dspeed** [comment]
No Thats not possible because ottoman in fact is a Object that can handle only one connection but you can have more then one ottoman instance example would look like this to make it clear:

~~~
// Empty object to make both instances access able via one object could be splitted
var couchbase = require('couchbase');
var cluster = new couchbase.Cluster('couchbase://127.0.0.1');

var ottoman = {}
ottoman.bucket1 = require('ottoman');
ottoman.bucket1.bucket = cluster.openBucket('default');

ottoman.bucke2 = require('ottoman');
ottoman.bucket2.bucket = cluster.openBucket('default');

~~~

**Comment by moxious** [comment]
Disagree -- you can put any model in any bucket, with one ottoman instance.  But you have to do one extra step:

```
var cluster = new couchbase.Cluster('couchbase://127.0.0.1');
var myBucket = cluster.openBucket('default');
var couchbaseAdapter = new ottoman.StoreAdapter.Couchbase(myBucket);

var model = couchbase.model('MyModel', { field: 'string' },
   { 
      store: couchbaseAdapter,
      index: { /* whatever */ }
   });
```

When you set `ottoman.bucket` to something, behind the scenes ottoman is turning that into a CouchbaseAdapter just as above.  By default when you create a model, if you haven't specified an adapter then ottoman will use whatever is on `ottoman.bucket`.  But if you do specify a `store` attribute in your model options and make it a couchbase adapter, your model will end up wherever you specify.

**Comment by moxious** [comment]
**Warning** -- this should still be a legitimate issue but maybe needs to be recategorized.  While my comment above is accurate and you can put models in different buckets, there is some index creation mechanics which tends to assume all models are in the same bucket.  This means that there are probably edge cases particularly with the creation of n1ql indices where if you had 10 models in 2 buckets (5 in each) it's possible to end up with 10 indexes created on the first bucket only, leaving the remaining model un-indexed.

It has to do with where/when CbStoreAdapter.prototype._ensureGsiIndices gets called, which is inherently bucket specific rather than model specific.

**Comment by frank-dspeed** [comment]
Littel question why do you then comment because my method works 100% even with this edge cases i am wondering because it looks simple like my inital comment was 100% accurate.

**Comment by rikantro** [comment]
If I want to create two models (users and posts) in different buckets; It´s possible to have this entities in a nested model  ?

**Comment by frank-dspeed** [comment]
hmmmm good question try it and give me the result i think it should be possible because the way javascript objects work

**Comment by kivervinicius** [comment]
Hello, for this case you have any other solution? because I tried both ways and not of right, I did something.

```
var configBD = require("../config.json"),
    couchbase = require("couchbase");

var cluster = new couchbase.Cluster(configBD.couchbase.server);

var connections = {};
connections.c1 = require("ottoman");
connections.c1.bucket = cluster.openBucket("c1", configBD.couchbase.password);
connections.c1.storeAdapter = new connections.c1.StoreAdapter.Couchbase(connections.c1.bucket);

connections.captcha = require("ottoman");
connections.captcha.bucket = cluster.openBucket("captcha", configBD.couchbase.password);

connections.analytics = require("ottoman");
connections.analytics.bucket = cluster.openBucket("analytics", configBD.couchbase.password);
```

As mentioned by @frank-dspeed , but it did not work. All instances of the ottoman are connected to the analytics database.

Then I made under the direction of @moxious , about to set store on models, and it is the same problem, there would be some easier way to implement this, I enjoyed the framework, and liked to continue using it

**Comment by moxious** [comment]
@kivervinicius what you're doing with re-requiring ottoman and putting a new bucket on each isn't going to work because of this: https://github.com/couchbaselabs/node-ottoman/blob/master/lib/ottoman.js#L1045

When you require ottoman, it creates the ottoman instance and returns it.  When you require it the second time, it doesn't get evaluated.   This is because of how nodejs "require" works.  A simple example:

Tiny module named "t.js":
```
console.log('Foo!');
module.exports = 1;
```

Then try to require it twice:
```
$ node
> var t = require('./t');
Foo!
undefined
> var u = require('./t');
undefined
> 
```

Node doesn't re-evaluate the file when you require the second time, so you're stuck with the first instance of the ottoman object you're using.  In this case then you're just assigning a different bucket to it 3 times, so it always ends with the last one.

**Comment by kivervinicius** [comment]
@moxious tks for great explanation, but how i can resolve this? I think clone this repository and return a instance inves classe.

**Comment by kivervinicius** [comment]
@moxious  all right, I could make it work, but it is to agree that it is not something very elegant in any way thank you for the replies and attention.

**Comment by brett19** [comment]
Hey Guys,
The answer is actually a lot simpler than the suggestions above.  You can create as many Ottoman instances as you desire, they just won't be directly accessible.  For convenience, the Ottoman.js module returns a already-constructed Ottoman object, but you can create more, here is an example:

```javascript
var ottoman = require('ottoman');
var ottoman2 = new ottoman.Ottoman();
var ottoman3 = new ottoman.Ottoman();
ottoman.store = ...;
ottoman2.store = ...;
ottoman3.store = ...;
```

Cheers, Brett

**Comment by kivervinicius** [comment]
Thanks @brett19 i will add this on readme for next questions.

**Comment by kivervinicius** [comment]
Thanks @brett19, better now
