### ISSUE TITLE
Alternative to leading underscore for custom properties.

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/node-ottoman#79]
Using underscore as a leading character for Ottoman fields (_type, _id, etc) breaks compatibility with Sync Gateway.  Having a configuration option to use something other than underscore as the leading character would allow users to combine Ottoman and Sync Gateway.  

Several users have hit this issue:
https://forums.couchbase.com/t/sync-gateway-and-ottoman-driven-shadow-unable-to-sync/7344
https://www.thepolyglotdeveloper.com/2016/02/building-a-cea2n-and-nativescript-application-webinar-series/#comment-2563962025

**Comment by DanlanNZ** [comment]
@ToddGreenstein @brett19 any update on this? happy to help with a solution.
I'm currently migrating an API to use ottoman from [couch-cushion](https://github.com/jfelsinger/couch-cushion) for a bucket that is being shadowed by SyncGateway, would like to solve this before rolling if possible

**Comment by brett19** [comment]
Hey @DanlanNZ ,
We are still having ongoing discussions on how to best solve this problem as there is a pretty direct conflict between Sync Gateway and Ottoman.js.  We have some direction, but are not quite there yet.
Cheers, Brett

**Comment by CelsoSantos** [comment]
Hello @brett19 , not wanting to be a PITA and knowing that you guys are working very hard on this issue I still have to ask if there's any envisioned time-frame for when to expect this?

I'm building a solution which requires CBSG and I'd very much appreciate the ability to keep Ottoman in the stack since it would make the work so much easier.

Is there any ugly-hack we could use right now to "just" getting working while a propper solution is in the works?

Best Regards,
CS

**Comment by brett19** [comment]
Hey @CelsoSantos ,
The only 'ugly hack' you could currently do would be to fork ottoman and search-replace all instance of `_type` and `_id`.  I would sincerely discourage this though.
Cheers, Brett

**Comment by moxious** [comment]
@brett19  above, you said:

> We are still having ongoing discussions on how to best solve this problem as there is a pretty direct conflict between Sync Gateway and Ottoman.js. We have some direction, but are not quite there yet.

Can you elaborate on this?

A relatively obvious way to fix this would be to do some minor refactoring, replace all instances of _type with some variable like a `typeDesignator`, then set that to be equal to _type by default, with the caller option to configure it at ottoman singleton creation time.

I'll admit this is a bit simplistic/naive approach, but I know it would work **and** maintain backwards compatibility.   Could you expand on what approaches you're thinking about?   This problem doesn't seem to me on the surface to be so complicated to solve.

At the end of the day ottoman has to have some field to store this info.  And it has to know what that field is, and that field probably should be consistent across all models (otherwise it would be a mess to configure this per-model).   But at least providing the option to use something other than `_type` seems pretty easy.  What am I missing?

**Comment by brett19** [comment]
It is totally reasonable, and in the end I expect we will do something along these lines.  We are however preferring to simply fix the logic so that they do not conflict in the first place, but we need to define some kind of standard for that first.
Cheers, Brett

**Comment by moxious** [comment]
I can imagine that a lot of tools based on couchbase need a way to reserve some special fields for their use.  If you have a better option that involves coordination with those other tools or coming up with a more general solution other than making the developer deconflict things manually when problems arise, that would be preferrable.

**Comment by brett19** [comment]
That's the plan, and why this ticket is still open instead of simply making _type configurable. 👍

P.S. To be fair, making it configurable is probably not a bad first step.

**Comment by CelsoSantos** [comment]
Hello everyone,

Just a quick update. Find and replace all does **not** work. It will make Ottoman start spitting out errors.
Replacements can be done, but don't just find and replace.

**Comment by stecapra** [comment]
Any news? Is it possible to use ottoman with sync gateway now?

**Comment by gsi-chao** [comment]
In ottoman v2 it is already possible to configure the _type parameter. Check https://v2.ottomanjs.com/guides/model.html#model-options for more details
