### ISSUE TITLE
Don't use eval

### ISSUE THREAD

**Issue by moxious** [couchbaselabs/node-ottoman#93]
https://github.com/couchbaselabs/node-ottoman/blob/master/lib/ottoman.js#L675

This should be refactored, it doesn't look like there's a real need to use eval to define a model function (since it is bound to a variable "model" anyway).  This introduces unnecessary dependencies (like syntactic validity of the name of the model as a javascript function) and is also quite a bit slower since you need to invoke javascript interpreter mechanics.

There's a second use of eval that looks inappropriate here: https://github.com/couchbaselabs/node-ottoman/blob/master/lib/schema.js#L356

In this case eval is used to define a string!

**Comment by brett19** [comment]
The reasoning for the two uses of eval here are:
ottoman.js: This is an eval statement so that the error messages that show up in stack traces correctly identify the name of the model you were working with rather not having any name.  V8 does not always allow you to set the 'Function.name' parameter, so the only option is to evaluate a function declaration.
schema.js: This predates having any of the ottoman path parsing, and we needed to allow nested fields to be selected which does not work with just `object[path]`.
Cheers, Brett
